version: '3'
services:
  backup-database:
    image: tungvt200576/backup-database
    container_name: backup-database
    environment:
      - HOSTNAME=192.168.0.125
      - BACKUP_DATABASE=mci
      - PG_USERNAME=dev
      - PG_PASSWORD=1
      - CRON_EXPRESSION="0 * * * *"
      - SCHEMA=mci-dev
    volumes:
      - /home/das/backup:/data
    restart: always
