name: Build, Push, Ssh, Pull, Down, Up

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: tungvt200576/backup-database:1.0


  pull-and-up:
    name: Pull new image and re run with the new version
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH into server and pull new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker pull tungvt200576/backup-database:1.0

      - name: Stop and remove existing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker stop backup-database || true
            docker rm backup-database || true

      - name: Start the new container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker run --env HOSTNAME=192.168.0.125 \
            --env ROOT_DATABASE=mci \
            --env PG_USERNAME=dev \
            --env PG_PASSWORD=1 \
            --env CRON_EXPRESSION="* * * * *" \
            --volume /home/das/backup:/data \
            --name backup-database \
            -d tungvt200576/backup-database:1.0